requirejs.config({
	baseUrl: 'src/',
	paths: {
		lodash: '../components/lodash/dist/lodash.compat',
		playcraft: '../components/playcraft/playcraftjs/lib',
		jquery: '../components/jquery/dist/jquery',
		virtualjoystick: '../components/virtualjoystick/index',
		text: '../components/requirejs-text/text'
	},
	// enforceDefine: true,
	shim: {
		'playcraft/ext/gamecore.js/src/class': ['playcraft/ext/gamecore.js/src/gamecore'],
		'playcraft/ext/gamecore.js/src/base': ['playcraft/ext/gamecore.js/src/gamecore'],
		'playcraft/ext/gamecore.js/src/jhashtable': ['playcraft/ext/gamecore.js/src/gamecore'],
		'playcraft/ext/gamecore.js/src/device': ['playcraft/ext/gamecore.js/src/gamecore'],
		'playcraft/ext/gamecore.js/src/perf': ['playcraft/ext/gamecore.js/src/gamecore'],
		'playcraft/ext/gamecore.js/src/linkedlist': ['playcraft/ext/gamecore.js/src/gamecore'],
		'playcraft/ext/gamecore.js/src/hashlist': ['playcraft/ext/gamecore.js/src/gamecore'],
		'playcraft/ext/gamecore.js/src/stacktrace': ['playcraft/ext/gamecore.js/src/gamecore'],
		'playcraft/ext/gamecore.js/src/pooled': ['playcraft/ext/gamecore.js/src/gamecore'],
		'playcraft/boot': ['playcraft/ext/gamecore.js/src/gamecore', 'playcraft/ext/gamecore.js/src/class', 'playcraft/ext/gamecore.js/src/base', 'playcraft/ext/gamecore.js/src/jhashtable', 'playcraft/ext/gamecore.js/src/device', 'playcraft/ext/gamecore.js/src/perf', 'playcraft/ext/gamecore.js/src/linkedlist', 'playcraft/ext/gamecore.js/src/hashlist', 'playcraft/ext/gamecore.js/src/stacktrace', 'playcraft/ext/gamecore.js/src/pooled', 'playcraft/ext/box2dweb.2.1a-pc'],
		'playcraft/input': ['playcraft/boot'],
		'playcraft/hashmap': ['playcraft/boot'],
		'playcraft/tools': ['playcraft/boot'],
		'playcraft/color': ['playcraft/boot'],
		'playcraft/debug': ['playcraft/boot'],
		'playcraft/device': ['playcraft/boot'],
		'playcraft/sound': ['playcraft/boot'],
		'playcraft/layer': ['playcraft/boot'],
		'playcraft/entitylayer': ['playcraft/boot'],
		'playcraft/tileset': ['playcraft/boot'],
		'playcraft/tilemap': ['playcraft/boot'],
		'playcraft/tilelayer': ['playcraft/boot'],
		'playcraft/hextilelayer': ['playcraft/boot'],
		'playcraft/entity': ['playcraft/boot'],
		'playcraft/sprite': ['playcraft/boot'],
		'playcraft/spritesheet': ['playcraft/boot'],
		'playcraft/math': ['playcraft/boot'],
		'playcraft/image': ['playcraft/boot'],
		'playcraft/scene': ['playcraft/boot'],
		'playcraft/game': ['playcraft/boot'],
		'playcraft/loader': ['playcraft/boot'],
		'playcraft/dataresource': ['playcraft/boot'],
		'playcraft/components/component': ['playcraft/boot'],
		'playcraft/components/physics': ['playcraft/boot'],
		'playcraft/components/alpha': ['playcraft/boot'],
		'playcraft/components/joint': ['playcraft/boot'],
		'playcraft/components/expiry': ['playcraft/boot'],
		'playcraft/components/originshifter': ['playcraft/boot'],
		'playcraft/components/spatial': ['playcraft/boot'],
		'playcraft/components/overlay': ['playcraft/boot'],
		'playcraft/components/clip': ['playcraft/boot'],
		'playcraft/components/activator': ['playcraft/boot'],
		'playcraft/components/input': ['playcraft/boot'],
		'playcraft/components/fade': ['playcraft/boot'],
		'playcraft/components/spin': ['playcraft/boot'],
		'playcraft/components/scale': ['playcraft/boot'],
		'playcraft/components/rect': ['playcraft/boot'],
		'playcraft/components/poly': ['playcraft/boot'],
		'playcraft/components/circle': ['playcraft/boot'],
		'playcraft/components/text': ['playcraft/boot'],
		'playcraft/components/sprite': ['playcraft/boot'],
		'playcraft/components/layout': ['playcraft/boot'],
		'playcraft/components/particleemitter': ['playcraft/boot'],
		'playcraft/systems/system': ['playcraft/boot'],
		'playcraft/es/entitymanager': ['playcraft/boot'],
		'playcraft/es/systemmanager': ['playcraft/boot'],
		'playcraft/systems/entitysystem': ['playcraft/boot'],
		'playcraft/systems/physics': ['playcraft/boot'],
		'playcraft/systems/effects': ['playcraft/boot'],
		'playcraft/systems/particles': ['playcraft/boot'],
		'playcraft/systems/input': ['playcraft/boot'],
		'playcraft/systems/expiry': ['playcraft/boot'],
		'playcraft/systems/activation': ['playcraft/boot'],
		'playcraft/systems/render': ['playcraft/boot'],
		'playcraft/systems/layout': ['playcraft/boot']
	}
});


require(['bootstrap']);
// 	function (pc, Archers) {
// 		console.log('dsadasd');
// 		debugger;
// 		window.Archers = Archers;
// 		pc.device.boot('game', 'Archers');
// });